### DISCUSSION TITLE
Pass plugin parameter through flakeheaven?

### DISCUSSION THREAD

**Discussion by FyZzyss** [flakeheaven/flakeheaven#129] [Q&A] [answered]
I'm trying to add a parameter max-try-body-length=10, but it's not working. If I simply use `flake8 src --max-try-body-length=10` everything is okey. How I can fix this?
```
[tool.flakeheaven.plugins]
pycodestyle = ["-*"]
pyflakes = ["+*"]
flake8-annotations = ["+*"]
wemake-python-styleguide = ["+*", "--max-try-body-length=10", "-WPS507"]
```

**Comment by pwoolvett** [comment, marked as answer]
Flake8 configuration goes in the main `tool.flakeheaven` section, not inside plugins

```toml
[tool.flakeheaven]
max-try-body-length = 10

[tool.flakeheaven.plugins]
pycodestyle = ["-*"]
pyflakes = ["+*"]
flake8-annotations = ["+*"]
wemake-python-styleguide = ["+*", "-WPS507"]
```

**Reply by FyZzyss** [reply]
Oh, thank you. I am new with flakehaeaven

**Reply by pwoolvett** [reply]
No problem 👍
Check out https://flakeheaven.readthedocs.io/en/latest/config.html

And feel free to contribute buy opening a PR with improvements in the future!

**Reply by FyZzyss** [reply]
@pwoolvett One more question, please! Is there an example for pre-commit?
I tried following:
```
 - repo: https://github.com/flakeheaven/flakeheaven
    rev: 2.1.3
    hooks:
       - id: flakeheaven
         stages:
           - commit
           - push
         args: [.]
```
 And in any case, there is a check, even if it has not been changed.py files from my baseline, but another linters skipped 
 pycln................................................(no files to check)Skipped
