### ISSUE TITLE
Plugin options can't be defined in pyproject.toml

### ISSUE THREAD

**Issue by mondeja** [flakeheaven/flakeheaven#103]
I've found that I can't put options for third party plugins like `flake8-doctrings`. This configuration is not recognized in a *pyproject.toml* file:

```toml
[tool.flakeheaven]
docstring-convention = "numpy"
```

So I need to put in the `flake8` section of a *setup.cfg*, *.flake8* or *tox.ini* file. But that would force me to put the configuration in different files or pass CLI arguments. Couldn't this be handled by flakeheaven? Thanks!
