### ISSUE TITLE
pyproject.toml plugins config fields differ from flake8

### ISSUE THREAD

**Issue by mondeja** [flakeheaven/flakeheaven#105]
Here is a reproducible example: [workflow run](https://github.com/mondeja/flakeheaven-error-repr/runs/6726909719?check_suite_focus=true) and [repository](https://github.com/mondeja/flakeheaven-error-repr).

*pyproject.toml*

```toml
[tool.flakeheaven]
# default value is "list"
pytest-parametrize-values-type = "tuple"

[tool.flakeheaven.plugins]
flake8-pytest-style = ["+*"]
```

Example file *test_foo.py*:

```python
@pytest.mark.parametrize(
    ('foo', 'bar'),
    (
        (1, 2),  # I'm using tuples for values, so should pass
        (3, 4),
    )
)
def test_foo():
    pass
```

Execution from *main* branch (disabling cache):

```sh
$ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint
test_foo.py:1:2: PT007 wrong values type in @pytest.mark.parametrize, expected list of tuples [flake8-pytest-style]
```

Should pass but is not working.

Note that passes if I run it with command line arguments:

```sh
$ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint --pytest-parametrize-values-type=tuple
$ echo $?
0
```
