### ISSUE TITLE
Complexity warnings do not show up

### ISSUE THREAD

**Issue by astromancer** [flakeheaven/flakeheaven#120]
I have a file with some complex functions that trigger a warning in `flake8`:
```shell
❯ flake8 src/analytics/calcs.py --ignore=E501,E741,D202,W291,W503,Q000 --max-complexity=10 -vv 2>flake8.log
src/analytics/calcs.py:222:1: C901 'volatility_decay' is too complex (13)
```
However, I can't seem to get the warning to show up with flakeheaven. Here's my config in `pyproject.toml`:
```toml
[tool.flakeheaven]
max_line_length = 99
# check cyclomatic complexity (mccabe). Currently not working with flakeheaven
max_complexity = 10

# make output nice
format = "grouped"

[tool.flakeheaven.plugins]
"flake8-*" = ["+*", "-Q000", "-D202", "+C901"]
```
I ran the following from the shell:
```shell
❯ flakeheaven lint src/floatdata/analytics/vol_decay_calcs.py -vv 2>flakeheaven.log
```
which does not report the `C901` despite explicitly adding it. Passing `--max-complexity=10` also gives no result.

Here's the diff view of the output logs
![Screenshot from 2022-07-02 22-44-41](https://user-images.githubusercontent.com/5623552/177015719-90867a92-1af8-4802-a24e-ed9097aec28f.png)
:

The `Extended default select list` seems like the crucial bit that's missing.
