### ISSUE TITLE
baseline.txt not working for large files

### ISSUE THREAD

**Issue by benjhastings** [flakeheaven/flakeheaven#137]
I have an extremely complex legacy project that I'm trying to implement flakeheaven on - along with the wemake style templates and want the checks to run through pre-commit

**.pre-commit-config.yaml**

```
default_stages: [commit, manual]
repos:
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.0.0
    hooks:
      - id: flakeheaven
        entry: flakeheaven lint
        additional_dependencies: [
          wemake-python-styleguide
        ]
```

**pyproject.toml**
```
[tool.flakeheaven]
baseline = "baseline.txt"

[tool.flakeheaven.plugins]
# These plugins get installed by `wekmake-python-styleguide` as defined in pre-commit-config.
"flake8-*" = ["+*", "-Q000"]
"py*" = ["+*"]
pep8-naming = ["+*"]
mccabe = ["+*"]
wemake-python-styleguide = ["+*"]
```

I have generated a baseline file by doing the following:

* manually installing flakeheaven by doing `pip install flakeheaven==3.0.0`
* running `flakeheaven baseline > baseline.txt` (this file is about 5000 lines long!)
* `poetry install --sync` (as I want pre-commit to manage the flakeheaven version so don't want it in my env)

**The problem**

When I try and make changes to any of the legacy files, flakeheaven reports errors on many lines - not just the ones that I changed. I assumed that this was happening because I was (for example) adding a new method in the middle of the file and flakeheaven was picking up the new line numbers of the second half of the file as a change. But I've tried adding a new function right at the bottom of the file and flakeheaven still reports errors elsewhere in the file that were previously ignored due to the baseline.

* I've proven the baseline works if I undo any changes then run `flakeheaven lint <path/to/file.py>`.
* I've tried this exact same flow on a dummy project with only a 20 line "legacy" file that has issues and flakeheaven correctly reports errors **only** where I have changed code - correctly ignoring any functions that have issues that I haven't changed.

Does anyone have any suggestions of how I can get this working? My only guess is that the size/complexity is the problem here.
