### ISSUE TITLE
BUG: `--config` should be a `flakeheaven` global argument, not just a `flakeheaven lint` one

### ISSUE THREAD

**Issue by stdedos** [flakeheaven/flakeheaven#141]
**Checklist**

* [x] Same issue occurs when reproducing the MWE below: new virtualenv, clean folder, minimal additional libs, etc.
* [x] Same issue occurs when running without cache (eg by setting the env var `FLAKEHEAVEN_CACHE_TIMEOUT=0`)

**Bug Description**

```console
$ flakeheaven plugins --config=flakeheaven-base.toml
NAME                          | VERSION  | CODES            | RULES
flake8-bugbear                | 22.9.23  | B                | +*, -W503
flake8-class-attributes-order | 0.1.3    | CCE              | +*, -W503
flake8-docstrings             | 1.6.0    | D                | +*
flake8-type-checking          | 2.1.3    | TC               | +*, -W503
mccabe                        | 0.6.1    | C90              | +*
pycodestyle                   | 2.8.0    | E, W             | +*
pyflakes                      | 2.4.0    | F                | 
pylint                        | 2.15.2   | C, E, F, I, R, W | 
$ flakeheaven plugins -h
NAME                          | VERSION  | CODES            | RULES
flake8-bugbear                | 22.9.23  | B                | +*, -W503
flake8-class-attributes-order | 0.1.3    | CCE              | +*, -W503
flake8-docstrings             | 1.6.0    | D                | +*
flake8-type-checking          | 2.1.3    | TC               | +*, -W503
mccabe                        | 0.6.1    | C90              | +*
pycodestyle                   | 2.8.0    | E, W             | +*
pyflakes                      | 2.4.0    | F                | 
pylint                        | 2.15.2   | C, E, F, I, R, W | 
```

```toml
[tool.flakeheaven]
# Make output nice
format = "grouped"
show_source = true

# Black compatible settings
max_line_length = 120
extend_ignore = ["E203"]

# Suppress exceptions from plugin (the exception will be converted into E902 error)
safe = true

extend_exclude = [
    ".venv",
]

# list of plugins and rules for them
[tool.flakeheaven.plugins]
"flake8-*" = ["+*", "-W503"]
mccabe = ["+*"]
pycodestyle = ["+*"]
```
and
```toml
[tool.flakeheaven]
base = "flakeheaven-base.toml"

[tool.flakeheaven.plugins]
flake8-docstrings = ["+*"]
```

**Expected behavior**

**Bug Repro**

1. OS, arch
2. `python --version`
3. `pyproject.toml` (and / or all other config files that apply, eg `.pylintrc`, stc)
4. `pip freeze`
5.  `flakeheaven plugins`
6. Contents of any additional files (eg sample `.py` file(s) to be linted)
7. Any additional env vars setup
8. [If available] contents of `flakeheaven config -vvv`

1. run `flakeheaven ...`
2. ...

**Additional context**

_Source: https://discord.com/channels/927757025193099375/927757025193099378/threads/1027501357080530954_
