### ISSUE TITLE
Feature Request: add more flexibility in plugins configuration

### ISSUE THREAD

**Issue by MaximZayats** [flakeheaven/flakeheaven#148]
Hi!
Maybe I misunderstood something, but it is possible to configure each plugin directly ?

Example:
```python
# file.py
f = "test"
```

```toml
[tool.flakeheaven]
good-names = ["f"]

[tool.flakeheaven.plugins]
pylint = ["+*", "-C011?", "-R0903"]

[tool.pylint."BASIC"]
good-names = ["f"]
```

```
-> flakeheaven lint .\file.py
-> file.py:1:1: C0103 Constant name "f" doesn't conform to UPPER_CASE naming style (invalid-name) [pylint]
```

But at the same time, pylint uses the `good-names = ["f"]`:
```
-> pylint file.py
-> file.py:1:0: C0114: Missing module docstring (missing-module-docstring)

------------------------------------------------------------------
```

So, is it possible to configure `flakeheaven` to pass additional options to plugins (like `good-names = ["f"]`) ?

**Comment by MaximZayats** [comment]
After I run `flakeheaven` with `FLAKEHEAVEN_CACHE_TIMEOUT=0` the issue seems to be resolved.
```
FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint setup.py
```

```toml
[tool.pylint."BASIC"]
good-names = ["f"]

[tool.flakeheaven]


[tool.flakeheaven.plugins]
pylint = ["+*", "-C011?", "-R0903"]

```
