### ISSUE TITLE
flakeheaven plugins --config=myconfig.toml isn't honoured

### ISSUE THREAD

**Issue by commentator8** [flakeheaven/flakeheaven#65]
When i run `flakeheaven plugins --config=myconfig.toml` and expect to see my settings picked up instead I see all my plugins as red with no codes shown. When I manually move the contents of that file (I have it there because I use a shared definition for many projects) to the end of my pyproject.toml and rerun - it works.

**Comment by notpushkin** [comment]
You can add it as a base config, e. g.:

```toml
[tool.flakeheaven]
base = ["./myconfig.toml"]
```

Or even remote:

```toml
[tool.flakeheaven]
base = ["https://gitlab.com/aedge/flakeheaven-config/-/raw/main/flakeheaven.toml"]
```
