### ISSUE TITLE
Bug - glob exceptions from base config do not get overwritten by more specific local ones

### ISSUE THREAD

**Issue by Cielquan** [flakeheaven/flakeheaven#74]
I have a base config with has an exception with globs to activate specific flake8 plugins for test files only and deactivate other rules:

```toml
...
[tool.flakeheaven.exceptions."**/test_*.py"]
flake8-aaa = ["+*"]
flake8-bandit = ["-S101"]
```
[source](https://github.com/Cielquan/my-flake8-plugins/blob/main/flakeheaven-base.toml#L56-L61)

In a project I set this file as `base` and add another exception which is specific to a single file:
```toml
[tool.flakeheaven.exceptions."tests/test_rstcheck.py"]
flake8-aaa = ["-AAA01"]
```

But I still get multiple errors from this file like this:
```
tests/test_rstcheck.py:503:5: AAA01 no Act block found in test [flake8-aaa]
```

EDIT: I use the latest release version.
EDIT2: On master this is also the case. 6138285ed808c334c9cb175e2a1f97dfb3cb679a

**Comment by Cielquan** [comment]
Another case I have is this:

I added to the repo config from above
```toml
[tool.flakeheaven.exceptions."tests/test_as_cli_tool.py"]
flake8-bandit = ["-S603", "-S607"]
```

And I still get errors for both codes from the file `tests/test_as_cli_tool.py`.

**Comment by mcarans** [comment]
If you have time to look into the code to see how this could be fixed, we would be happy to receive a PR.

**Comment by Cielquan** [comment]
I just recently took over maintenance for another open source project which currently consumes all my available time, besides my own project(s).
This issue also currently has no high priority for me.
Therefore it may take a while till I can deal with this issue.

**Comment by vkurilin** [comment]
Maybe I could take a look. But we need to specify how we want to treat this "conflicts":

- Strive to select the most specific exception. Seems to be quite a challenge to determine what we call the most "specific" rule.
- Simply concatenate every exception block that matches the current file. The only downside I see here is that it's obviously a breaking change and if a project uses a lot of glob-based exceptions, it will be difficult to figure out which set of rules will ultimately be applied to the file. It may even make sense to make a cli command for this.

I personally find the second approach more intuitive and therefore preferable. What are your thoughts?

**Comment by Cielquan** [comment]
Concatenation sound good so far. I would also like to have the base config apply but be able to add additional config in the project like described above.

But what would this case result in?

In base:
```toml
[tool.flakeheaven.exceptions."**/test_*.py"]
flake8-aaa = ["+AAA01"]
```

In project:
```toml
[tool.flakeheaven.exceptions."tests/test_rstcheck.py"]
flake8-aaa = ["-AAA01"]
```

I don't know the internals of flakeheaven so I don't know.
I guess that a more specific config like `-AAA01` overwrites a generic `+*`. But does the search for best match end at the first full match found? So basicly if I have `["+*", "+AAA01", "-AAA01"]` would this result in `+AAA01` or `-AAA01`?
I think for overwriting purposes it would be good to take the last best match I guess? So that you can overwrite the base config with the local one.

**Comment by vkurilin** [comment]
If you asking about actual behaviour, the best word to describe it is ["magic" (link to source)](https://github.com/flakeheaven/flakeheaven/blob/main/flakeheaven/_logic/_plugin.py#L132-L152).


Let's call exceptions whose path contains as "*" glob-exceptions. All others will be called prefix-exceptions.
It works like this:
- any matching glob-exception overrides prefix-exception rules for the same plugin;
- among exceptions of the same type, the exception with the shortest path overrides all other rules for the same plugin.

Let's imagine that we have exceptions with the following paths, and filename matches them all:
`'*/path', '*/path/path', 'prefix/', 'prefix/prefix'`.

Rules of `prefix/prefix` would be overwritten by the rules of `prefix/`. They, in turn, will be overwritten by the rules `*/path/path` because glob always beats prefix, and finally, rules of  '*/path' would be applied, because it is the shortest glob.

So in your example, with current logic, would be applied `flake8-aaa = ["+AAA01"]`.

**Comment by Cielquan** [comment]
Then IMO this should be changed. Lets make an experiment:

## Setup

Lets assume we have the following file structure.

File tree:
```
root
└─ dir_1
   └─ dir_1_1
      └─ file_1.py
   └─ dir_1_2
      └─ file_2.py
```

This means we have two files:
- `root/dir_1/dir_1_1/file_1.py`
- `root/dir_1/dir_1_2/file_2.py`


## Example prefix

When we have the following exceptions:
```toml
[tool.flakeheaven.exceptions."root/dir_1"]
flake8-aaa = ["+AAA01"]

[tool.flakeheaven.exceptions."root/dir_1/dir_1_2"]
flake8-aaa = ["-AAA01"]
```
This would result in `+AAA01` for both files, because the upper exception has a shorter prefix. If I would see this config without knowledge I would assume that `file_2.py` has `-AAA01` and `file_1.py` has `+AAA01`, would you not?


## Example glob

When we have the following exceptions:
```toml
[tool.flakeheaven.exceptions."*/dir1"]
flake8-aaa = ["+AAA01"]

[tool.flakeheaven.exceptions."*/dir_1/dir_1_2"]
flake8-aaa = ["-AAA01"]
```
This would again result in `+AAA01` for both files, because the upper exception has a shorter glob. If I would see this config without knowledge I would again assume that `file_2.py` has `-AAA01` and `file_1.py` has `+AAA01`, would you not?


## Example prefix vs glob

When we have the following exceptions:
```toml
[tool.flakeheaven.exceptions."*/dir1"]
flake8-aaa = ["+AAA01"]

[tool.flakeheaven.exceptions."root/dir_1/dir_1/dir_1_2"]
flake8-aaa = ["-AAA01"]
```
This would again result in `+AAA01` for both files, because the upper exception has is a glob even so it matches less good for `file_2.py`. If I would see this config without knowledge I would again assume that `file_2.py` has `-AAA01` and `file_1.py` has `+AAA01`, would you not?


## Conclusion

So in all three cases the result is against intuition.

I think it would be better to take the longest matching prefix/glob instead of the shortest, because elsewise you cannot overwrite deeper nested exceptions.

I also think it is no good to let globs take precedence over prefixes by default.

If I have an error in my thought experiment please tell me.
